PUT http://localhost/catalog-search
Content-Type: application/json

{
  "mappings": {
    "properties": {
      "document-name": { "type": "string" },
      "document-text": { "type": "string" },
      "document-size": { "type": "long", "index": false }
    }
  }
}